export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const BOOKS_SCREEN = 'BOOKS_SCREEN';
export const BORROW_SCREEN = 'BORROW_SCREEN';
export const VIEW_BOOK_SCREEN = 'VIEW_BOOK_SCREEN';
